// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDTZWVx6nVU9_PS6DXoFujdsYRPnrbSXQ',
    appId: '1:350193877658:web:239e0866ba428d17159523',
    messagingSenderId: '350193877658',
    projectId: 'totod-d4f99',
    authDomain: 'totod-d4f99.firebaseapp.com',
    storageBucket: 'totod-d4f99.appspot.com',
    measurementId: 'G-4WSVP7C0JW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd5MHM325XA3n2gzMgOK4ad5Lta8Iqahw',
    appId: '1:350193877658:android:7cb736eda2ade28c159523',
    messagingSenderId: '350193877658',
    projectId: 'totod-d4f99',
    storageBucket: 'totod-d4f99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5JnpzaR4K81w5QXEDiEX0XsHzKuvHjWY',
    appId: '1:350193877658:ios:e3337e1126d96dc3159523',
    messagingSenderId: '350193877658',
    projectId: 'totod-d4f99',
    storageBucket: 'totod-d4f99.appspot.com',
    iosBundleId: 'com.example.toDolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5JnpzaR4K81w5QXEDiEX0XsHzKuvHjWY',
    appId: '1:350193877658:ios:e3337e1126d96dc3159523',
    messagingSenderId: '350193877658',
    projectId: 'totod-d4f99',
    storageBucket: 'totod-d4f99.appspot.com',
    iosBundleId: 'com.example.toDolist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDTZWVx6nVU9_PS6DXoFujdsYRPnrbSXQ',
    appId: '1:350193877658:web:8e3c6e2445e5276e159523',
    messagingSenderId: '350193877658',
    projectId: 'totod-d4f99',
    authDomain: 'totod-d4f99.firebaseapp.com',
    storageBucket: 'totod-d4f99.appspot.com',
    measurementId: 'G-CZ0WTMNMQ4',
  );
}
